config/routes.rb
Rails.application.routes.draw do

  root 'tanks#index'

  resources :tanks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tank.rb
class Tank < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tanks_controller.rb
class TanksController < ApplicationController

  def index
    @tanks = Tank.all

    respond_to do |format|
        format.html
        format.json { render json: @tanks }
      end
  end

  def show
    @tank = Tank.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @tank }
    end
  end

  def new
    @tank = Tank.new
  end

  def edit
    @tank = Tank.find(params[:id])
  end

  def create
    @tank = Tank.new(tank_params)

    if @tank.save
      flash[:notice] = "Tank created!"
      redirect_to @tank
    else
      flash.now[:notice] = "Tank couldn't be created."
      render 'new'
    end
  end

  def update
    @tank = Tank.find(params[:id])

    if @tank.update(tank_params)
      flash[:notice] = "Tank updated!"
      redirect_to @tank
    else
      flash.now[:notice] = "Tank couldn't be updated."
      render 'edit'
    end
  end

  def destroy
    @tank = Tank.find(params[:id])
    @tank.destroy
    flash[:notice] = "Tank has been deleted!"

    redirect_to tanks_path
  end

    private

    def tank_params
      params.require(:tank).permit(:address)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tanks_helper.rb
module TanksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TankApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tanks/create.html.erb
<h1>Tanks#create</h1>
<p>Find me in app/views/tanks/create.html.erb</p>

app/views/tanks/edit.html.erb
<h1>Edit article</h1>

<%= form_with(model: @tank, local: true) do |form| %>

  <% if @tank.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tank.errors.count, "error") %> prohibited
        this tank from being saved:
      </h2>
      <ul>
        <% @tank.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', tanks_path %>

app/views/tanks/index.html.erb
<% if notice %>
  <p ><%= notice %></p>
<% end %>

<table>
  <tr>
    <th>Address</th>
    <th></th>
  </tr>

  <% @tanks.each do |tank| %>
    <tr>
      <td><%= tank.address %></td>
      <td><%= link_to 'Show', tank_path(tank) %></td>
      <td><%= link_to 'Edit', edit_tank_path(tank) %></td>
      <td><%= link_to 'Destroy', tank_path(tank),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'All Tanks', controller: 'tanks' %>
<%= link_to 'New Tank', new_tank_path %>

app/views/tanks/new.html.erb
<h1>Tanks#new</h1>
<%= form_with scope: :tank, url: tanks_path, local: true do |form| %>
  <p>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', tanks_path %>

app/views/tanks/show.html.erb
<% if notice %>
  <p ><%= notice %></p>
<% end %>

<p>
  <strong>Tank Address:</strong>
  <%= @tank.address %>
</p>

<%= link_to 'Edit', edit_tank_path(@tank) %> |
<%= link_to 'Back', tanks_path %>

app/views/tanks/update.html.erb
<h1>Tanks#update</h1>
<p>Find me in app/views/tanks/update.html.erb</p>